'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { Dumbbell, ArrowLeft, Upload, Check, AlertCircle } from 'lucide-react';
import Link from 'next/link';

export default function ImportRoutinePage() {
  const router = useRouter();
  const [jsonInput, setJsonInput] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [validationErrors, setValidationErrors] = useState<Array<{ path: string; message: string }>>([]);

  const handleImport = async () => {
    setLoading(true);
    setError(null);
    setValidationErrors([]);

    let parsed;
    try {
      parsed = JSON.parse(jsonInput);
    } catch {
      setError('Invalid JSON format. Please check your input.');
      setLoading(false);
      return;
    }

    try {
      const res = await fetch('/api/routines', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(parsed),
      });

      const data = await res.json();

      if (!res.ok) {
        if (data.details && Array.isArray(data.details)) {
          setValidationErrors(data.details.map((d: { path: string; message: string }) => ({ path: d.path, message: d.message })));
        }
        setError(data.message || 'Failed to import routine');
        setLoading(false);
        return;
      }

      // Success - redirect to the routine
      router.push(`/routines/${data.routine_id}`);
    } catch (err) {
      setError('Failed to import routine');
      console.error(err);
      setLoading(false);
    }
  };

  const exampleRoutine = `{
  "schema_version": "1.0",
  "title": "4-Week Strength Base",
  "duration_weeks": 4,
  "days_per_week": 3,
  "goals": ["strength"],
  "equipment": ["barbell", "rack"],
  "weeks": [
    {
      "week_number": 1,
      "days": [
        {
          "day_number": 1,
          "title": "Full Body A",
          "focus": ["squat", "press"],
          "exercises": [
            {
              "exercise_id": "sq1",
              "name": "Back Squat",
              "movement_pattern": "squat",
              "primary_muscles": ["quadriceps", "glutes"],
              "rest_seconds": 180,
              "sets": [
                { "set_number": 1, "reps": 5, "target_rpe": 8 },
                { "set_number": 2, "reps": 5, "target_rpe": 8 },
                { "set_number": 3, "reps": 5, "target_rpe": 8 }
              ]
            }
          ]
        }
      ]
    }
  ]
}`;

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <header className="bg-white shadow-sm border-b">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-between items-center h-16">
            <div className="flex items-center">
              <Link href="/dashboard" className="flex items-center">
                <Dumbbell className="h-8 w-8 text-blue-600 mr-3" />
                <span className="text-xl font-semibold text-gray-900">AI Trainer</span>
              </Link>
            </div>
            <button
              onClick={() => router.push('/')}
              className="text-sm text-gray-500 hover:text-gray-700 transition-colors"
            >
              Home
            </button>
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main className="max-w-3xl mx-auto py-8 px-4 sm:px-6">
        <Link
          href="/routines"
          className="inline-flex items-center text-sm text-gray-600 hover:text-gray-900 mb-6"
        >
          <ArrowLeft className="h-4 w-4 mr-1" />
          Back to Routines
        </Link>

        <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-6">
          <h1 className="text-2xl font-bold text-gray-900 mb-2">Import Routine</h1>
          <p className="text-gray-600 mb-6">
            Paste a routine JSON generated by an LLM or copy the example below.
          </p>
          <Link
            href="/prompts"
            className="inline-flex text-sm text-blue-600 hover:text-blue-700 mb-4"
          >
            Need help crafting the LLM prompt? Open Prompt Compiler
          </Link>

          {error && (
            <div className="bg-red-50 border border-red-200 rounded-lg p-4 text-red-700 mb-4">
              <div className="flex items-start">
                <AlertCircle className="h-5 w-5 mr-2 flex-shrink-0 mt-0.5" />
                <div>
                  <p className="font-medium">{error}</p>
                  {validationErrors.length > 0 && (
                    <ul className="mt-2 text-sm space-y-1">
                      {validationErrors.map((e, i) => (
                        <li key={i}>
                          <code className="text-red-600">{e.path || '(root)'}</code>: {e.message}
                        </li>
                      ))}
                    </ul>
                  )}
                </div>
              </div>
            </div>
          )}

          <div className="mb-4">
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Routine JSON
            </label>
            <textarea
              value={jsonInput}
              onChange={(e) => setJsonInput(e.target.value)}
              placeholder="Paste your routine JSON here..."
              rows={15}
              className="w-full px-3 py-2 border border-gray-300 rounded-lg font-mono text-sm focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
            />
          </div>

          <div className="flex flex-col sm:flex-row gap-3">
            <button
              onClick={handleImport}
              disabled={loading || !jsonInput.trim()}
              className="flex-1 flex items-center justify-center bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700 transition-colors disabled:opacity-50"
            >
              {loading ? (
                <div className="h-5 w-5 animate-spin rounded-full border-2 border-white border-t-transparent mr-2" />
              ) : (
                <Upload className="h-5 w-5 mr-2" />
              )}
              {loading ? 'Importing...' : 'Import Routine'}
            </button>

            <button
              onClick={() => setJsonInput(exampleRoutine)}
              className="flex items-center justify-center bg-gray-100 text-gray-700 px-4 py-2 rounded-lg hover:bg-gray-200 transition-colors"
            >
              <Check className="h-5 w-5 mr-2" />
              Load Example
            </button>
          </div>
        </div>

        <div className="mt-6 bg-blue-50 border border-blue-200 rounded-lg p-4">
          <h3 className="font-medium text-blue-900 mb-2">How to generate a routine</h3>
          <ol className="text-sm text-blue-800 space-y-1 list-decimal list-inside">
            <li>Go to your favorite LLM (ChatGPT, Claude, etc.)</li>
            <li>Use the prompt compiler in this app</li>
            <li>Describe your goals, equipment, and constraints</li>
            <li>Paste the export instruction to get valid JSON</li>
            <li>Copy the JSON output and paste it here</li>
          </ol>
        </div>
      </main>
    </div>
  );
}
