import catalog from "./exercises.generated.json";

// Data generated by scripts/build-exercise-catalog.mjs
// Sources: free-exercise-db, exercemus, longhaul-strength, longhaul-flexibility, plus snapshots in scripts/sources/ and curated entries.
export type ExerciseCatalogItem = {
  id: string;
  name: string;
  aliases: string[];
  equipment: string[];
  movementPatterns: string[];
  muscles: {
    primary: string[];
    secondary: string[];
  };
  tags: string[];
};

export const exerciseCatalog: ExerciseCatalogItem[] = catalog;
