import catalog from "./exercises.generated.json";

export type {
  DisambiguationRule,
  GeneratedArtifact,
  ImportDisambiguation,
  ModifierCategory,
  MovementDefinition,
  MovementModifierDefinition,
} from "./registries";

// Data generated by scripts/build-exercise-catalog.mjs
// Sources: free-exercise-db, exercemus, longhaul-strength, longhaul-flexibility, plus snapshots in scripts/sources/ and curated entries.
export type ExerciseCatalogItem = {
  id: string;
  name: string;
  aliases: string[];
  equipment: string[];
  movementPatterns: string[];
  muscles: {
    primary: string[];
    secondary: string[];
  };
  tags: string[];
  movementId?: string;
  movementModifierIds: string[];
};

export const exerciseCatalog: ExerciseCatalogItem[] = catalog.map((item) => ({
  ...item,
  movementId: item.movementId ?? undefined,
  movementModifierIds: item.movementModifierIds ?? [],
}));
