import catalog from "./exercises.generated.json";

// Data generated by scripts/build-exercise-catalog.mjs from https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/dist/exercises.json.
export type ExerciseCatalogItem = {
  id: string;
  name: string;
  aliases: string[];
  equipment: string[];
  movementPatterns: string[];
  muscles: {
    primary: string[];
    secondary: string[];
  };
  tags: string[];
};

export const exerciseCatalog: ExerciseCatalogItem[] = catalog;
